package pers.quan.exception;

public class ExceptionTest {
	public static void main(String[] args) {
		try {
			int[] arr = new int[2];
			System.out.println(arr[4]);
			System.out.println("后续");
		}catch(IndexOutOfBoundsException e) {
			e.getStackTrace();
			System.out.println("越界访问");
//			e.getMessage();
		}catch(NullPointerException e) {
			System.out.println("空指针");
			e.getMessage();
		}
		
		System.out.println("结果");
		
		
	}
}
